[workspace]
members = ["boot"]

[package]
name = "sabios"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.10.3"
conquer-once = {version = "0.3.2", default-features = false}
spin = "0.9.0"
