[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
kbuild = "build --target x86_64-sabios.json -Z build-std=core,alloc"
krun = "run --target x86_64-sabios.json -Z build-std=core,alloc"
